// <auto-generated />
using System;
using MarketplaceAnalytics.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MarketplaceAnalytics.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MarketplaceAnalyticsDbContext))]
    partial class MarketplaceAnalyticsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("marketplace_analytics")
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MarketplaceAnalytics.Infrastructure.Persistence.DatabaseFoundationMarker", b =>
                {
                    b.Property<short>("Id")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id")
                        .HasName("pk_database_foundation_marker");

                    b.ToTable("database_foundation_marker", "marketplace_analytics", t =>
                        {
                            t.Property("Id")
                                .HasColumnName("id");

                            t.Property("CreatedAtUtc")
                                .HasColumnName("created_at_utc");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
